Repository DSM-DMS/NMS-Backend-V1, pull requests merged in 2021-12, with the labels that each got.

#93 🔀 :: (#92) 상속 관계 매핑
  src/main/java/com/dsm/nms/domain/reply/facade/ReplyFacade.java
  src/main/java/com/dsm/nms/domain/student/entity/Student.java
  src/main/java/com/dsm/nms/domain/teacher/entity/Teacher.java
  src/main/java/com/dsm/nms/global/entity/Writer.java
Labels: 버그

#95 🔀 :: (#94) 토큰 재발급
  src/main/java/com/dsm/nms/domain/refreshtoken/entity/RefreshToken.java
  src/main/java/com/dsm/nms/domain/refreshtoken/repository/RefreshTokenRepository.java
  src/main/java/com/dsm/nms/domain/student/api/StudentController.java
  src/main/java/com/dsm/nms/domain/student/service/StudentService.java
  src/main/java/com/dsm/nms/domain/student/service/StudentServiceImpl.java
  src/main/java/com/dsm/nms/domain/teacher/api/TeacherController.java
  src/main/java/com/dsm/nms/domain/teacher/service/TeacherService.java
  src/main/java/com/dsm/nms/domain/teacher/service/TeacherServiceImpl.java
  src/main/java/com/dsm/nms/global/security/jwt/JwtProperties.java
  src/main/java/com/dsm/nms/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/dsm/nms/global/utils/auth/user/UserUtil.java
Labels: 기능 추가

#99 🔀 :: (#91) 선생님 프로필
  src/main/java/com/dsm/nms/domain/auth/api/AuthController.java
  src/main/java/com/dsm/nms/domain/auth/service/password/PasswordService.java
  src/main/java/com/dsm/nms/domain/auth/service/password/StudentPasswordService.java
  src/main/java/com/dsm/nms/domain/auth/service/password/TeacherPasswordService.java
  src/main/java/com/dsm/nms/domain/student/entity/Student.java
  src/main/java/com/dsm/nms/domain/teacher/api/TeacherController.java
  src/main/java/com/dsm/nms/domain/teacher/api/dto/response/ProfileResponse.java
  src/main/java/com/dsm/nms/domain/teacher/entity/Teacher.java
  src/main/java/com/dsm/nms/domain/teacher/facade/TeacherFacade.java
  src/main/java/com/dsm/nms/domain/teacher/service/TeacherService.java
  src/main/java/com/dsm/nms/domain/teacher/service/TeacherServiceImpl.java
  src/main/java/com/dsm/nms/global/security/SecurityConfig.java
Labels: 기능 추가

#102 🔀 :: (#101) 자잘
  src/main/java/com/dsm/nms/domain/auth/api/AuthController.java
  src/main/java/com/dsm/nms/domain/notice/api/NoticeController.java
  src/main/java/com/dsm/nms/domain/reply/api/ReplyController.java
  src/main/java/com/dsm/nms/domain/reply/api/dto/request/ReplyRequest.java
  src/main/java/com/dsm/nms/domain/star/api/StarController.java
  src/main/java/com/dsm/nms/domain/student/api/StudentController.java
  src/main/java/com/dsm/nms/domain/teacher/api/TeacherController.java
Labels: 버그, 리팩토링

#104 🔀 :: (#96) 학생정보 수정
  src/main/java/com/dsm/nms/domain/auth/service/AuthCodeServiceImpl.java
  src/main/java/com/dsm/nms/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/dsm/nms/domain/reply/service/ReplyServiceImpl.java
  src/main/java/com/dsm/nms/domain/student/api/StudentController.java
  src/main/java/com/dsm/nms/domain/student/entity/Student.java
  src/main/java/com/dsm/nms/domain/student/service/StudentService.java
  src/main/java/com/dsm/nms/domain/student/service/StudentServiceImpl.java
  src/main/java/com/dsm/nms/global/utils/auth/user/UserUtil.java
Labels: 기능 추가

#105 🔀 :: (#98) 선생님 마이페이지
  src/main/java/com/dsm/nms/domain/notice/entity/Notice.java
  src/main/java/com/dsm/nms/domain/notice/repository/NoticeRepository.java
  src/main/java/com/dsm/nms/domain/notice/service/NoticeServiceImpl.java
  src/main/java/com/dsm/nms/domain/star/api/StarController.java
  src/main/java/com/dsm/nms/domain/star/repository/StarRepository.java
  src/main/java/com/dsm/nms/domain/star/service/StarService.java
  src/main/java/com/dsm/nms/domain/star/service/StarServiceImpl.java
  src/main/java/com/dsm/nms/domain/student/facade/StudentFacade.java
  src/main/java/com/dsm/nms/domain/teacher/api/TeacherController.java
  src/main/java/com/dsm/nms/domain/teacher/api/dto/response/MyPageResponse.java
  src/main/java/com/dsm/nms/domain/teacher/api/dto/response/ProfileResponse.java
  src/main/java/com/dsm/nms/domain/teacher/service/TeacherService.java
  src/main/java/com/dsm/nms/domain/teacher/service/TeacherServiceImpl.java
Labels: 기능 추가

#107 🔀 :: (#106) 공지사항 수정
  src/main/java/com/dsm/nms/domain/image/facade/ImageFacade.java
  src/main/java/com/dsm/nms/domain/teacher/api/dto/response/MyPageResponse.java
  src/main/java/com/dsm/nms/domain/teacher/service/TeacherServiceImpl.java
Labels: 리팩토링

#108 🔀 :: (#90) 학생 마이페이지
  src/main/java/com/dsm/nms/domain/comment/entity/Comment.java
  src/main/java/com/dsm/nms/domain/student/api/StudentController.java
  src/main/java/com/dsm/nms/domain/student/api/dto/request/SignUpRequest.java
  src/main/java/com/dsm/nms/domain/student/api/dto/response/MyPageResponse.java
  src/main/java/com/dsm/nms/domain/student/service/StudentService.java
  src/main/java/com/dsm/nms/domain/student/service/StudentServiceImpl.java
  src/main/java/com/dsm/nms/domain/teacher/api/dto/response/MyPageResponse.java
  src/main/java/com/dsm/nms/global/entity/Writer.java
Labels: 기능 추가

#111 🔀 :: (#97) 선생님 정보 수정
  src/main/java/com/dsm/nms/domain/student/api/StudentController.java
  src/main/java/com/dsm/nms/domain/teacher/api/TeacherController.java
  src/main/java/com/dsm/nms/domain/teacher/api/dto/request/TeacherInfoRequest.java
  src/main/java/com/dsm/nms/domain/teacher/api/dto/response/MyPageResponse.java
  src/main/java/com/dsm/nms/domain/teacher/api/dto/response/ProfileResponse.java
  src/main/java/com/dsm/nms/domain/teacher/entity/Teacher.java
  src/main/java/com/dsm/nms/domain/teacher/service/TeacherService.java
  src/main/java/com/dsm/nms/domain/teacher/service/TeacherServiceImpl.java
Labels: 기능 추가

#114 🔀 :: (#113) Bearer 토큰 검사
  src/main/java/com/dsm/nms/global/security/jwt/JwtTokenProvider.java
Labels: 버그, 기능 추가

#116 🔀 :: (#115) 이메일 인증 오류
  src/main/java/com/dsm/nms/domain/auth/entity/AuthCode.java
  src/main/java/com/dsm/nms/domain/auth/facade/AuthCodeFacade.java
  src/main/java/com/dsm/nms/domain/auth/service/AuthCodeServiceImpl.java
Labels: 버그

#112 🔀 :: (#59) 공지사항 조회
  src/main/java/com/dsm/nms/domain/notice/api/NoticeController.java
  src/main/java/com/dsm/nms/domain/notice/repository/NoticeTargetRepository.java
  src/main/java/com/dsm/nms/domain/notice/service/NoticeService.java
  src/main/java/com/dsm/nms/domain/notice/service/NoticeServiceImpl.java
  src/main/java/com/dsm/nms/domain/student/api/StudentController.java
  src/main/java/com/dsm/nms/domain/teacher/api/TeacherController.java
Labels: 기능 추가

#117 🔀 :: (#110) 도커파일 생성
  Dockerfile
Labels: 프로젝트 설정

#120 🔀 :: (#119) 선생님 토큰 버그
  src/main/java/com/dsm/nms/domain/teacher/repository/TeacherRepository.java
  src/main/java/com/dsm/nms/global/security/auth/TeacherDetailsService.java
Labels: 버그

#122 🔀 :: (#121) 즐겨찾기 여부 판단
  src/main/java/com/dsm/nms/domain/star/facade/StarFacade.java
Labels: 버그

#124 🔀 :: (#123) 즐겨찾기 개수 & Path Variable 오류
  src/main/java/com/dsm/nms/domain/notice/api/NoticeController.java
  src/main/java/com/dsm/nms/domain/notice/api/dto/response/NoticeResponse.java
  src/main/java/com/dsm/nms/domain/notice/service/NoticeServiceImpl.java
  src/main/java/com/dsm/nms/domain/star/facade/StarFacade.java
  src/main/java/com/dsm/nms/domain/star/repository/StarRepository.java
Labels: 버그, 기능 추가

#118 🔀 :: (#109) S3 이미지 배치작업
  build.gradle
  src/main/java/com/dsm/nms/NmsBackendV1Application.java
  src/main/java/com/dsm/nms/domain/image/repository/ImageRepository.java
  src/main/java/com/dsm/nms/domain/notice/api/dto/request/ModifyNoticeRequest.java
  src/main/java/com/dsm/nms/domain/notice/api/dto/request/RegisterNoticeRequest.java
  src/main/java/com/dsm/nms/domain/notice/facade/NoticeFacade.java
  src/main/java/com/dsm/nms/domain/student/facade/StudentFacade.java
  src/main/java/com/dsm/nms/domain/teacher/facade/TeacherFacade.java
  src/main/java/com/dsm/nms/global/batch/BatchConfig.java
  src/main/java/com/dsm/nms/global/batch/UniqueIdGenerator.java
  src/main/java/com/dsm/nms/global/batch/scheduled/S3Scheduler.java
  src/main/java/com/dsm/nms/global/utils/aws/s3/S3Util.java
  src/main/resources/application.yml
Labels: 버그, 기능 추가

#126 🔀 :: (#125) Security Permission 설정
  src/main/java/com/dsm/nms/global/security/SecurityConfig.java
Labels: 버그

#128 🔀 :: (#127) 댓글과 답글 개수 나누기
  src/main/java/com/dsm/nms/domain/comment/facade/CommentFacade.java
  src/main/java/com/dsm/nms/domain/notice/api/dto/response/NoticeResponse.java
  src/main/java/com/dsm/nms/domain/notice/facade/NoticeFacade.java
  src/main/java/com/dsm/nms/domain/notice/service/NoticeServiceImpl.java
  src/main/java/com/dsm/nms/domain/reply/facade/ReplyFacade.java
Labels: chore

#129 🔀 :: (#110) Docker Compose
  Dockerfile
  docker-compose.yml
Labels: 기능 추가

#131 🔀 :: (#130) 작성자와 댓글/답글 간의 연관관계 설정
  src/main/java/com/dsm/nms/domain/comment/entity/Comment.java
  src/main/java/com/dsm/nms/domain/reply/entity/Reply.java
  src/main/java/com/dsm/nms/global/entity/Writer.java
Labels: 버그, chore

#133 🔀 :: (#132) docker-compose yaml파일 수정
  docker-compose.yml
Labels: chore

#135 🔀 :: (#134) InvalidRole 처리
  src/main/java/com/dsm/nms/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/dsm/nms/domain/reply/service/ReplyServiceImpl.java
  src/main/resources/application.yml
Labels: 버그

#136 🔀 :: NPE
  src/main/java/com/dsm/nms/domain/notice/entity/Notice.java
Labels: 버그

#138 🔀 :: (#137) 마이페이지 학번수정
  src/main/java/com/dsm/nms/domain/student/api/dto/response/MyPageResponse.java
  src/main/java/com/dsm/nms/domain/student/exception/InvalidGradeException.java
  src/main/java/com/dsm/nms/domain/student/service/StudentServiceImpl.java
  src/main/java/com/dsm/nms/global/error/ErrorCode.java
  src/main/resources/application.yml
Labels: 기능 추가, chore

#140 🔀 :: (#139) 작성자 pk값 보여주기
  src/main/java/com/dsm/nms/domain/notice/api/dto/response/NoticeResponse.java
  src/main/java/com/dsm/nms/domain/notice/service/NoticeServiceImpl.java
Labels: 기능 추가

#142 🔀 :: (#141) 이메일 인증 로직수정
  src/main/java/com/dsm/nms/domain/auth/service/AuthCodeServiceImpl.java
Labels: 버그

#144 🔀 :: (#143) 공지사항 등록
  src/main/java/com/dsm/nms/domain/notice/service/NoticeServiceImpl.java
Labels: 버그

#146 🔀 :: (#145) 즐겨찾기 버그
  src/main/java/com/dsm/nms/domain/star/facade/StarFacade.java
  src/main/java/com/dsm/nms/domain/star/service/StarServiceImpl.java
Labels: 버그

#148 🔀 :: (#147) 마이페이지 버그
  src/main/java/com/dsm/nms/domain/star/repository/StarRepository.java
  src/main/java/com/dsm/nms/domain/student/service/StudentServiceImpl.java
Labels: 버그

#150 🔀 :: 149 Hibernate Query 방지
  src/main/resources/application.yml
Labels: chore

#152 🔀 :: (#151) IndexOutOfBoundsException우회
  src/main/java/com/dsm/nms/domain/student/api/dto/response/MyPageResponse.java
  src/main/java/com/dsm/nms/domain/student/service/StudentServiceImpl.java
Labels: 버그

#154 🔀 :: (#153) 이미지 처리 시 NPE 방지
  src/main/java/com/dsm/nms/domain/student/service/StudentServiceImpl.java
  src/main/java/com/dsm/nms/domain/teacher/service/TeacherServiceImpl.java
  src/main/java/com/dsm/nms/global/utils/auth/user/UserUtil.java
Labels: 버그

#156 🔀 :: (#155) 댓글 및 답글 작성자 pk값
  src/main/java/com/dsm/nms/domain/comment/facade/CommentFacade.java
  src/main/java/com/dsm/nms/domain/reply/facade/ReplyFacade.java
Labels: chore

#157 🔀 :: (#60) 공지사항 조회 최종
  src/main/java/com/dsm/nms/domain/comment/facade/CommentFacade.java
  src/main/java/com/dsm/nms/domain/notice/api/NoticeController.java
  src/main/java/com/dsm/nms/domain/notice/api/dto/response/SchoolResponse.java
  src/main/java/com/dsm/nms/domain/notice/api/dto/response/SuburbResponse.java
  src/main/java/com/dsm/nms/domain/notice/entity/DevEvent.java
  src/main/java/com/dsm/nms/domain/notice/repository/DevEventRepository.java
  src/main/java/com/dsm/nms/domain/notice/service/NoticeService.java
  src/main/java/com/dsm/nms/domain/notice/service/NoticeServiceImpl.java
  src/main/java/com/dsm/nms/domain/reply/facade/ReplyFacade.java
Labels: 기능 추가
