Repository DSM-DMS/NMS-Backend-V1, pull requests merged in 2021-11, with the labels that each got.

#38 #28 이미지 엔티티 수정
  src/main/java/com/dsm/nms/entity/image/Image.java
Labels: enhancement

#47 🔀 :: (#46) jwt 기본설정
  build.gradle
  src/main/java/com/dsm/nms/NmsBackendV1Application.java
  src/main/java/com/dsm/nms/global/security/jwt/JwtProperties.java
  src/main/java/com/dsm/nms/global/security/jwt/JwtTokenFilter.java
  src/main/java/com/dsm/nms/global/security/jwt/JwtTokenProvider.java
  src/main/resources/application.yml
Labels: 기능 추가

#45 🔀 :: (#43) 예외 설정
  src/main/java/com/dsm/nms/global/error/ErrorCode.java
  src/main/java/com/dsm/nms/global/error/ErrorResponse.java
  src/main/java/com/dsm/nms/global/error/ExceptionFilter.java
  src/main/java/com/dsm/nms/global/error/GlobalExceptionHandler.java
  src/main/java/com/dsm/nms/global/error/exception/NmsException.java
  src/main/java/com/dsm/nms/global/exception/ExpiredTokenException.java
  src/main/java/com/dsm/nms/global/exception/InvalidTokenException.java
Labels: 기능 추가

#49 🔀 :: (#48) 필터 등록
  src/main/java/com/dsm/nms/global/error/ErrorCode.java
  src/main/java/com/dsm/nms/global/exception/InvalidRoleException.java
  src/main/java/com/dsm/nms/global/security/SecurityConfig.java
  src/main/java/com/dsm/nms/global/security/jwt/FilterConfig.java
  src/main/java/com/dsm/nms/global/security/jwt/JwtTokenFilter.java
  src/main/java/com/dsm/nms/global/security/jwt/JwtTokenProvider.java
Labels: 기능 추가

#51 🔀 :: (#50) 학번 컬럼 변경
  src/main/java/com/dsm/nms/domain/student/Student.java
  src/main/java/com/dsm/nms/global/config/WebMvcConfig.java
  src/main/java/com/dsm/nms/global/security/FilterConfig.java
  src/main/java/com/dsm/nms/global/security/SecurityConfig.java
Labels: 리팩토링

#58 🔀 :: (#41) 이메일 발송/인증
  build.gradle
  src/main/java/com/dsm/nms/domain/auth/api/AuthController.java
  src/main/java/com/dsm/nms/domain/auth/api/dto/request/SendCodeRequest.java
  src/main/java/com/dsm/nms/domain/auth/api/dto/request/VerifyCodeRequest.java
  src/main/java/com/dsm/nms/domain/auth/entity/AuthCode.java
  src/main/java/com/dsm/nms/domain/auth/entity/AuthCodeLimit.java
  src/main/java/com/dsm/nms/domain/auth/exception/AuthCodeAlreadyCertifiedException.java
  src/main/java/com/dsm/nms/domain/auth/exception/AuthCodeNotFoundException.java
  src/main/java/com/dsm/nms/domain/auth/exception/AuthCodeRequestOverLimitException.java
  src/main/java/com/dsm/nms/domain/auth/exception/InvalidAuthCodeException.java
  src/main/java/com/dsm/nms/domain/auth/facade/AuthCodeFacade.java
  src/main/java/com/dsm/nms/domain/auth/repository/AuthCodeLimitRepository.java
  src/main/java/com/dsm/nms/domain/auth/repository/AuthCodeRepository.java
  src/main/java/com/dsm/nms/domain/auth/service/AuthCodeService.java
  src/main/java/com/dsm/nms/domain/auth/service/AuthCodeServiceImpl.java
  src/main/java/com/dsm/nms/domain/student/exception/StudentAlreadyExistsException.java
  src/main/java/com/dsm/nms/domain/student/facade/StudentFacade.java
  src/main/java/com/dsm/nms/domain/teacher/api/TeacherController.java
  src/main/java/com/dsm/nms/domain/teacher/exception/TeacherAlreadyExistsException.java
  src/main/java/com/dsm/nms/domain/teacher/facade/TeacherFacade.java
  src/main/java/com/dsm/nms/domain/teacher/repository/TeacherRepository.java
  src/main/java/com/dsm/nms/global/error/ErrorCode.java
  src/main/java/com/dsm/nms/global/error/GlobalExceptionHandler.java
  src/main/java/com/dsm/nms/global/security/SecurityConfig.java
  src/main/java/com/dsm/nms/global/utils/aws/AwsProperties.java
  src/main/java/com/dsm/nms/global/utils/aws/ses/SesConfig.java
  src/main/java/com/dsm/nms/global/utils/aws/ses/SesUtils.java
  src/main/resources/application.yml
Labels: 기능 추가

#61 🔀 :: 리네임
  src/main/java/com/dsm/nms/domain/auth/api/AuthController.java
  src/main/java/com/dsm/nms/domain/auth/api/dto/request/CertifyCodeRequest.java
  src/main/java/com/dsm/nms/domain/auth/service/AuthCodeService.java
  src/main/java/com/dsm/nms/domain/auth/service/AuthCodeServiceImpl.java
Labels: 리팩토링

#62 🔀 :: (#56) 학생 / 선생님 비밀번호 확인 API
  src/main/java/com/dsm/nms/domain/auth/api/AuthController.java
  src/main/java/com/dsm/nms/domain/auth/api/dto/request/PasswordRequest.java
  src/main/java/com/dsm/nms/domain/auth/facade/AuthCodeFacade.java
  src/main/java/com/dsm/nms/domain/auth/service/AuthCodeServiceImpl.java
  src/main/java/com/dsm/nms/domain/auth/service/password/PasswordService.java
  src/main/java/com/dsm/nms/domain/auth/service/password/StudentPasswordService.java
  src/main/java/com/dsm/nms/domain/auth/service/password/TeacherPasswordService.java
  src/main/java/com/dsm/nms/domain/student/facade/StudentFacade.java
  src/main/java/com/dsm/nms/domain/teacher/exception/TeacherNotFouncException.java
  src/main/java/com/dsm/nms/domain/teacher/facade/TeacherFacade.java
  src/main/java/com/dsm/nms/global/error/ErrorCode.java
  src/main/java/com/dsm/nms/global/exception/InvalidPasswordException.java
  src/main/java/com/dsm/nms/global/utils/password/PasswordUtil.java
Labels: 기능 추가

#63 🔀 :: (#57) 학생 / 선생님 비밀번호 변경 API
  src/main/java/com/dsm/nms/domain/auth/api/AuthController.java
  src/main/java/com/dsm/nms/domain/auth/service/password/PasswordService.java
  src/main/java/com/dsm/nms/domain/auth/service/password/StudentPasswordService.java
  src/main/java/com/dsm/nms/domain/auth/service/password/TeacherPasswordService.java
  src/main/java/com/dsm/nms/domain/student/entity/Student.java
  src/main/java/com/dsm/nms/domain/student/exception/StudentNotFoundException.java
  src/main/java/com/dsm/nms/domain/student/facade/StudentFacade.java
  src/main/java/com/dsm/nms/domain/teacher/entity/Teacher.java
  src/main/java/com/dsm/nms/global/error/ErrorCode.java
Labels: 기능 추가

#64 🔀 :: (#40) 선생님 회원가입 api
  src/main/java/com/dsm/nms/domain/auth/service/password/StudentPasswordService.java
  src/main/java/com/dsm/nms/domain/auth/service/password/TeacherPasswordService.java
  src/main/java/com/dsm/nms/domain/student/repository/StudentRepository.java
  src/main/java/com/dsm/nms/domain/teacher/api/TeacherController.java
  src/main/java/com/dsm/nms/domain/teacher/api/dto/request/SignUpRequest.java
  src/main/java/com/dsm/nms/domain/teacher/entity/Teacher.java
  src/main/java/com/dsm/nms/domain/teacher/exception/UsernameAlreadyExistsException.java
  src/main/java/com/dsm/nms/domain/teacher/facade/TeacherFacade.java
  src/main/java/com/dsm/nms/domain/teacher/repository/TeacherRepository.java
  src/main/java/com/dsm/nms/domain/teacher/service/TeacherService.java
  src/main/java/com/dsm/nms/domain/teacher/service/TeacherServiceImpl.java
  src/main/java/com/dsm/nms/global/aop/Enum.java
  src/main/java/com/dsm/nms/global/aop/EnumValidator.java
  src/main/java/com/dsm/nms/global/error/ErrorCode.java
  src/main/java/com/dsm/nms/global/exception/EmailAlreadyExistException.java
  src/main/java/com/dsm/nms/global/security/SecurityConfig.java
  src/main/java/com/dsm/nms/global/utils/auth/password/PasswordUtil.java
  src/main/java/com/dsm/nms/global/utils/auth/user/UserUtil.java
Labels: 기능 추가

#65 🔀 :: (#55) 공지사항 작성 API
  src/main/java/com/dsm/nms/domain/auth/service/AuthCodeServiceImpl.java
  src/main/java/com/dsm/nms/domain/image/entity/Image.java
  src/main/java/com/dsm/nms/domain/image/exception/ImageNotFoundException.java
  src/main/java/com/dsm/nms/domain/image/facade/ImageFacade.java
  src/main/java/com/dsm/nms/domain/notice/entity/Notice.java
  src/main/java/com/dsm/nms/domain/notice/exception/TargetNotFoundException.java
  src/main/java/com/dsm/nms/domain/notice/facade/NoticeFacade.java
  src/main/java/com/dsm/nms/domain/notice/repository/TargetRepository.java
  src/main/java/com/dsm/nms/domain/notice/service/NoticeService.java
  src/main/java/com/dsm/nms/domain/notice/service/NoticeServiceImpl.java
  src/main/java/com/dsm/nms/domain/teacher/api/dto/request/RegisterNoticeRequest.java
  src/main/java/com/dsm/nms/domain/teacher/facade/TeacherFacade.java
  src/main/java/com/dsm/nms/global/config/S3Config.java
  src/main/java/com/dsm/nms/global/config/SesConfig.java
  src/main/java/com/dsm/nms/global/error/ErrorCode.java
  src/main/java/com/dsm/nms/global/exception/AuthenticationNotFoundException.java
  src/main/java/com/dsm/nms/global/exception/EmailAlreadyExistsException.java
  src/main/java/com/dsm/nms/global/utils/auth/user/UserUtil.java
  src/main/java/com/dsm/nms/global/utils/aws/AwsProperties.java
  src/main/java/com/dsm/nms/global/utils/aws/s3/S3Util.java
  src/main/java/com/dsm/nms/global/utils/aws/ses/SesUtil.java
  src/main/resources/application.yml
Labels: 기능 추가

#70 🔀 :: (#69) 공지 등록 컨트롤러
  src/main/java/com/dsm/nms/domain/notice/api/NoticeController.java
  src/main/java/com/dsm/nms/domain/notice/api/dto/RegisterNoticeRequest.java
  src/main/java/com/dsm/nms/domain/notice/entity/Notice.java
  src/main/java/com/dsm/nms/domain/notice/service/NoticeService.java
  src/main/java/com/dsm/nms/domain/notice/service/NoticeServiceImpl.java
  src/main/java/com/dsm/nms/domain/student/entity/Student.java
  src/main/java/com/dsm/nms/domain/teacher/api/dto/request/RegisterNoticeRequest.java
Labels: 버그, 기능 추가

#73 🔀 :: (#67) 학생 로그인
  src/main/java/com/dsm/nms/domain/refreshtoken/entity/RefreshToken.java
  src/main/java/com/dsm/nms/domain/student/api/StudentController.java
  src/main/java/com/dsm/nms/domain/student/api/dto/request/LoginRequest.java
  src/main/java/com/dsm/nms/domain/student/api/dto/request/SignUpRequest.java
  src/main/java/com/dsm/nms/domain/student/entity/Student.java
  src/main/java/com/dsm/nms/domain/student/service/StudentService.java
  src/main/java/com/dsm/nms/domain/student/service/StudentServiceImpl.java
  src/main/java/com/dsm/nms/domain/teacher/api/dto/request/SignUpRequest.java
  src/main/java/com/dsm/nms/global/security/SecurityConfig.java
  src/main/java/com/dsm/nms/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/dsm/nms/global/security/jwt/dto/response/TokenResponse.java
Labels: 기능 추가

#75 🔀 :: (#66) 공지사항 수정 API
  src/main/java/com/dsm/nms/domain/image/entity/Image.java
  src/main/java/com/dsm/nms/domain/image/facade/ImageFacade.java
  src/main/java/com/dsm/nms/domain/image/repository/ImageRepository.java
  src/main/java/com/dsm/nms/domain/notice/api/NoticeController.java
  src/main/java/com/dsm/nms/domain/notice/api/dto/ModifyNoticeRequest.java
  src/main/java/com/dsm/nms/domain/notice/entity/Notice.java
  src/main/java/com/dsm/nms/domain/notice/entity/target/Target.java
  src/main/java/com/dsm/nms/domain/notice/exception/NoticeNotFoundException.java
  src/main/java/com/dsm/nms/domain/notice/facade/NoticeFacade.java
  src/main/java/com/dsm/nms/domain/notice/service/NoticeService.java
  src/main/java/com/dsm/nms/domain/notice/service/NoticeServiceImpl.java
  src/main/java/com/dsm/nms/global/error/ErrorCode.java
  src/main/java/com/dsm/nms/global/security/SecurityConfig.java
  src/main/java/com/dsm/nms/global/utils/aws/s3/S3Util.java
Labels: 기능 추가

#78 🔀 :: (#74) 공지사항 삭제
  src/main/java/com/dsm/nms/domain/notice/api/NoticeController.java
  src/main/java/com/dsm/nms/domain/notice/facade/NoticeFacade.java
  src/main/java/com/dsm/nms/domain/notice/service/NoticeService.java
  src/main/java/com/dsm/nms/domain/notice/service/NoticeServiceImpl.java
  src/main/java/com/dsm/nms/domain/student/api/dto/request/SignUpRequest.java
Labels: 기능 추가

#80 🔀 :: (#76) 전체 공지사항 조회
  src/main/java/com/dsm/nms/domain/comment/entity/Comment.java
  src/main/java/com/dsm/nms/domain/comment/facade/CommentFacade.java
  src/main/java/com/dsm/nms/domain/comment/repository/CommentRepository.java
  src/main/java/com/dsm/nms/domain/image/entity/Image.java
  src/main/java/com/dsm/nms/domain/image/facade/ImageFacade.java
  src/main/java/com/dsm/nms/domain/notice/api/NoticeController.java
  src/main/java/com/dsm/nms/domain/notice/api/dto/request/ModifyNoticeRequest.java
  src/main/java/com/dsm/nms/domain/notice/api/dto/request/RegisterNoticeRequest.java
  src/main/java/com/dsm/nms/domain/notice/api/dto/response/NoticeResponse.java
  src/main/java/com/dsm/nms/domain/notice/entity/Notice.java
  src/main/java/com/dsm/nms/domain/notice/facade/NoticeFacade.java
  src/main/java/com/dsm/nms/domain/notice/repository/NoticeTargetRepository.java
  src/main/java/com/dsm/nms/domain/notice/service/NoticeService.java
  src/main/java/com/dsm/nms/domain/notice/service/NoticeServiceImpl.java
  src/main/java/com/dsm/nms/domain/reply/entity/Reply.java
  src/main/java/com/dsm/nms/domain/reply/facade/ReplyFacade.java
  src/main/java/com/dsm/nms/domain/reply/repository/ReplyRepository.java
  src/main/java/com/dsm/nms/domain/star/entity/Star.java
  src/main/java/com/dsm/nms/domain/star/facade/StarFacade.java
  src/main/java/com/dsm/nms/domain/star/repository/StarRepository.java
  src/main/java/com/dsm/nms/domain/student/facade/StudentFacade.java
  src/main/java/com/dsm/nms/domain/student/repository/StudentRepository.java
  src/main/java/com/dsm/nms/global/entity/BaseTimeEntity.java
  src/main/java/com/dsm/nms/global/entity/Writer.java
Labels: 기능 추가

#81 🔀 :: (#68) 선생님 로그인
  src/main/java/com/dsm/nms/domain/auth/service/password/TeacherPasswordService.java
  src/main/java/com/dsm/nms/domain/student/api/StudentController.java
  src/main/java/com/dsm/nms/domain/student/facade/StudentFacade.java
  src/main/java/com/dsm/nms/domain/teacher/api/TeacherController.java
  src/main/java/com/dsm/nms/domain/teacher/api/dto/request/LoginRequest.java
  src/main/java/com/dsm/nms/domain/teacher/api/dto/request/SignUpRequest.java
  src/main/java/com/dsm/nms/domain/teacher/entity/Teacher.java
  src/main/java/com/dsm/nms/domain/teacher/exception/TeacherNotFoundException.java
  src/main/java/com/dsm/nms/domain/teacher/facade/TeacherFacade.java
  src/main/java/com/dsm/nms/domain/teacher/service/TeacherService.java
  src/main/java/com/dsm/nms/domain/teacher/service/TeacherServiceImpl.java
Labels: 기능 추가

#85 🔀 :: (#84) 이메일 인증에 비동기 처리
  src/main/java/com/dsm/nms/domain/auth/service/AuthCodeServiceImpl.java
  src/main/java/com/dsm/nms/global/config/AsyncConfig.java
Labels: 기능 추가

#87 🔀 :: (#86) 댓글 개수 오류
  src/main/java/com/dsm/nms/domain/notice/service/NoticeServiceImpl.java
  src/main/java/com/dsm/nms/domain/reply/repository/ReplyRepository.java
Labels: 버그

#88 🔀 :: (#79) STAR
  src/main/java/com/dsm/nms/domain/star/api/StarController.java
  src/main/java/com/dsm/nms/domain/star/entity/Star.java
  src/main/java/com/dsm/nms/domain/star/exception/StarAlreadyExistsException.java
  src/main/java/com/dsm/nms/domain/star/exception/StarNotFoundException.java
  src/main/java/com/dsm/nms/domain/star/service/StarService.java
  src/main/java/com/dsm/nms/domain/star/service/StarServiceImpl.java
  src/main/java/com/dsm/nms/domain/teacher/entity/Teacher.java
  src/main/java/com/dsm/nms/global/error/ErrorCode.java
  src/main/java/com/dsm/nms/global/security/jwt/JwtTokenProvider.java
Labels: 버그, 기능 추가
